# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
name: tessellator
description: A Dart FFI wrapper for Impeller's tessellator.
version: 0.0.0
publish_to: none
homepage: https://github.com/flutter/impeller/tree/main/tessellator/dart

environment:
  sdk: '>=2.12.0 <3.0.0'
